spring:
  mvc:
   date-format: yyyy-MM-dd
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.15:3306/electricsystem?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
      # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml


